"""Rechange the field for chat model

Revision ID: db6449e036c1
Revises: 22a99c4232ad
Create Date: 2026-02-27 11:42:09.849944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db6449e036c1'
down_revision: Union[str, None] = '22a99c4232ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('temperature', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
